export const dynamic = 'force-static';
export default function Page(){return <><section className="hero"><div className="eyebrow">OPERATIONAL ASSURANCE FOR AI AGENTS</div><div className="hero-grid"><div><h1>You know how your agents work.<br/><em>Do you know how they fail?</em></h1><p className="hero-sub">We’re building RiskStriker to test complete AI agent systems under attack and service degradation. Measure what actually happens, verify which controls reduce the impact, and establish the tested conditions under which an agent remains within your risk tolerance.</p><div className="hero-actions"><a className="button" href="/riskstriker/">Explore the platform <span>↗</span></a><a className="button outline" href="/scenarios/">See test scenarios</a></div></div><div className="signal" aria-label="Proposed assurance method"><div className="signal-top">THE ASSURANCE LOOP</div><div className="signal-row"><span>01</span><strong>Set the red line</strong><b>CONTEXT</b></div><div className="signal-row"><span>02</span><strong>Attack and degrade</strong><b>SCENARIO</b></div><div className="signal-row"><span>03</span><strong>Trace the impact</strong><b>CONSEQUENCE</b></div><div className="signal-row"><span>04</span><strong>Retest the control</strong><b>EVIDENCE</b></div></div></div></section><div className="stripe"><span>CYBER + OPERATIONAL FAILURES</span><span>SYSTEM-LEVEL TESTING</span><span>CONTROL VERIFICATION</span></div><section className="section"><div className="section-head"><div className="section-label">BEYOND THE FINDING</div><div><h2>A prompt can fail.<br/>What did the system do?</h2><p>RiskStriker's proposed approach connects agent behaviour to downstream consequences, then tests what changes after remediation.</p></div></div><div className="grid3"><article><span className="number">01 / STRESS</span><h3>Challenge the whole system.</h3><p>Introduce malicious inputs, service outages, lost acknowledgements and degraded approval context across the agent, its tools and dependencies in an authorised test environment.</p></article><article><span className="number">02 / MEASURE</span><h3>Separate intent from impact.</h3><p>Track what the agent tried to do and what actually happened after the controls operated.</p></article><article><span className="number">03 / VERIFY</span><h3>Run it again. Compare.</h3><p>After your team changes a control, restore the starting conditions and rerun the identical scenario to measure whether impact falls.</p></article></div></section><section className="section"><div className="section-head"><div className="section-label">THE QUESTIONS THAT MATTER</div><div><h2>Evidence for your<br/>agent risk decisions.</h2><p>The planned assessment connects system context, stress testing and control verification to six practical questions.</p></div></div><div className="grid3">{[
['Which agents are operating?', 'Discover agents through connected sources and record the limits of discovery coverage.'],
['What can each agent affect?', 'Map the systems, data, permissions and actions within its reach.'],
['What outcomes are unacceptable?', 'Define risk tolerance and red lines for the specific agent and use case.'],
['What happens under pressure?', 'Measure actual consequences under attack, failure and service degradation.'],
['Which controls reduce the impact?', 'Compare the same scenario before and after customer remediation.'],
['Under which conditions is risk acceptable?', 'Record the tested configuration, autonomy and controls, alongside unresolved failures and inconclusive results.']
].map(([title,description])=><article key={title}><h3>{title}</h3><p>{description}</p></article>)}</div></section><section className="editorial"><div><div className="eyebrow">TEST SCENARIOS</div><h2>One agent.<br/>Several ways to fail.</h2></div><div><p>Explore three illustrative examples from fictional Department X covering data access, duplicate actions and approval failure. Each follows the fault, the consequence and the control to test.</p><a className="link-line" href="/scenarios/">Inside the test scenarios ↗</a></div></section><section className="product-panel"><div><div className="eyebrow">EVIDENCE YOU CAN EXAMINE</div><h2>Know what was tested.<br/>Know what wasn't.</h2></div><div><p>The planned evidence pack records configuration, autonomy, controls, test coverage, observed impact and remaining uncertainty. Results apply only to the conditions and scenarios assessed. Your organisation decides whether the remaining risk is acceptable.</p><a className="button outline" href="/evidence/">Explore the evidence approach ↗</a></div></section></>}
